### PR TITLE
static: rm almond and install via npm

### PR DESCRIPTION
**Pull request by yorkie**
This patch remove the static file `almond.js` and install this source file via npm :)

/cc @kenhkan

### CODE REVIEW

**Comment by kenhkan** [comment]
Actually, we can't do that. I had to modify almond.js to make it work as we need semantics parity with amdclean.

**Comment by kenhkan** [comment]
By semantics-parity I meant, it may work for a particular project, but it doesn't work completely with any project who may pass with amdclean.

**Comment by kenhkan** [comment]
I actually moved the change into scope, as seen [here](https://github.com/pixbi/duplo/commit/1801cd37e84355b985dea4eb925cf95f95b8661e). I was thinking that would be called by a duplo runtime but since change is necessary I thought we might as well just put the activation code directly into the file.

**Comment by yorkie** [comment]
Got it, and how about we create a package `almond-duplo` in npm, and make it as the dependency of duplo? haha, just wanna make the duplo as a pure haskell project as possible :)

**Comment by kenhkan** [comment]
What benefit would that bring? It still wouldn't receive patches from the original repo anyway.

I do like that mentality, but for a different reason. Personally I'd like to replace amdclean and jade more because they have created issues with semantics than purity. For example, if amdclean conforms to real AMD semantics of using `require()`, we wouldn't even need to change almondjs.

While I'm not opposed to the idea of separating it into its own repo, is there a strong reason behind doing so?

**Comment by yorkie** [comment]
ah, it's not strong, but just as what i said before, closing this and will look into issues of amdclean/almondjs/jade later

**Comment by kenhkan** [comment]
Nah. The issues that I mentioned are that bad. There're ways around them.

**Comment by yorkie** [comment]
:) Got them

**Pull request closed without merging**
